# Part 1 — Deterministic multi-period supply chain MILP

### Four things that look like economics and are really modelling choices

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sear-labs/advopt-lithiumsc/blob/main/notebooks/01_deterministic.ipynb)

A six-site network — two mines, two processors, two fabricators — serving two
regions over twenty years. One decision maker, perfect information, and lumpy
capacity that must be built in whole units. It is the simplest model in the
series and every later one is built on it.

The interesting content is not the model. It is that **four separate decisions
you have to make while building it will move the answer more than the data
does**:

| section | the choice | what it costs to get wrong |
|---|---|---|
| 8 | charge capex as a lump sum or an annuity | **+26%** on the objective, and 14× more unmet demand |
| 9 | how finely to discretise investment years | up to **+8%**, and not monotone in the number of years |
| 10 | learning: none, exogenous, or endogenous | exogenous is a **free lunch** the model will happily take |
| 11 | foresight window, and whether to ban tail investment | foresight is nearly free; the tail ban costs **+10.9%** |

Each of those is measured below, and each is a number a reader can check against
the output in the cell above it.

### The formulation

**Sets.** Sites $s$ (mines $\cup$ processors $\cup$ fabricators), regions $g$,
years $t$, decision years $v$, unit index $k$.

**Decisions.** $y_{s,v,k}\in\{0,1\}$ — build the $k$-th unit at site $s$, decided
in year $v$. Throughput $x_{s,v,t}\ge 0$, arc flows, and unmet demand $u_{g,t}$.

**Objective.**

$$\min \;\; \underbrace{\sum_{s,v,k}\pi_{s,v}\,c_{s}\,y_{s,v,k}}_{\text{capex}}
\;+\; \sum_t \delta_t\Big[\underbrace{\sum_s o_s x_{s,t}}_{\text{operating}}
+ \underbrace{\sum_{a,b}\tau_{ab}f_{ab,t}}_{\text{transport}}
+ \underbrace{\pi^{u}\sum_g u_{g,t}}_{\text{unmet}}\Big]$$

**The interesting coefficient is $\pi_{s,v}$**, the present value of \$1 of capex
for a facility decided in year $v$. Section 4 derives it, and section 8 shows
that the two defensible ways of computing it disagree by 26%.

### How to read this notebook

Sections 4 to 6 build the model by hand, one idea per cell. Section 7 wraps it
and checks the wrapper reproduces what you built. Section 12 asserts the notebook
and the `lithium` package agree to $10^{-9}$.

## 0. Setup

One cell, and it is the only place the `lithium` package appears before the final check. On Colab it
clones the repo and installs it; locally it assumes you have already run `pip install -e .` and just
moves up out of `notebooks/` so the relative data paths work.

In [1]:
import os
import subprocess
import sys
from pathlib import Path

REPO_URL = "https://github.com/sear-labs/advopt-lithiumsc.git"
# Forked or renamed? Change BOTH halves of that path. Only the owner ever
# looked like a placeholder, and the repo name beside it broke 64 URLs once.
REPO_NAME = REPO_URL.rstrip("/").split("/")[-1].replace(".git", "")

if "google.colab" in sys.modules:
    if not Path(REPO_NAME).exists():
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL], check=True)
    os.chdir(REPO_NAME)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-e", "."], check=True)
elif Path.cwd().name == "notebooks":
    os.chdir("..")

import gurobipy as gp
from gurobipy import GRB
import matplotlib.pyplot as plt
import pandas as pd

plt.rcParams.update({"font.size": 12, "axes.grid": True, "grid.alpha": 0.3})
print(f"working directory : {Path.cwd().name}")
print(f"gurobipy          : {gp.gurobi.version()}")
print(f"pandas            : {pd.__version__}")

working directory : Advanced Opt Modeling Examples
gurobipy          : (13, 0, 2)
pandas            : 2.3.3

## 2. The instance tables

Two kinds of number go into this model and they are treated differently.

A **knob** is a scalar carrying a concept — the discount rate, the asset life, the
learning rate. Knobs stay written out in the cell where they are explained, and
this notebook hands every one of them to the package in section 12, so the
agreement assertion covers them.

A **table** is instance data — many entries, indexed by the model's own sets,
named nowhere in the prose. Tables live in `data/raw/`, and both this notebook and
`src/lithium/` read the same file. Three tables:

| file | keyed by | rows |
|---|---|---|
| `network_sites.csv` | `site` | 6 |
| `network_tiers.csv` | `tier` | 2 |
| `network_demand.csv` | `region` | 2 |

**This is not the Part 4 instance.** Part 4's model is a two-region,
three-stage chain owned by competing *firms*; this is a six-site network owned by
one *planner*, with explicit arcs between sites. Both have a home region, an opex
and a lead time, which makes them easy to confuse — they share nothing.

Read the site table first and look at it as a **frame** — rows and columns —
before turning it into anything the model can index.

In [2]:
DATA = Path("data/raw")

if not (DATA / "network_sites.csv").exists():
    print("!" * 78)
    print("! data/raw/ was not found, so this notebook is FALLING BACK to generated")
    print("! numbers. Everything below will run and every figure will render, but the")
    print("! results are NOT the shipped instance and are NOT an acceptable submission.")
    print("! Fix: clone the repo (see section 0) or run this notebook from the repo root.")
    print("!" * 78)
    DATA = Path("_generated_fallback")
    DATA.mkdir(exist_ok=True)
    (DATA / "network_sites.csv").write_text(
        "site,tier,home,cap_unit,lead,capex0,opex,legacy_units,legacy_vintage,legacy_retire\n"
        "M1,M,R1,100,2,2000,1.3,2,-6,8\nM2,M,R2,100,2,2000,1.3,2,-6,8\n"
        "P1,P,R1,100,3,3200,2.1,2,-3,13\nP2,P,R2,100,3,3200,2.1,2,-3,13\n"
        "F1,F,R1,90,2,2800,2.4,2,-1,17\nF2,F,R2,90,2,2800,2.4,2,-1,17\n")
    (DATA / "network_tiers.csv").write_text(
        "tier,eta_bar,eta_0,alpha,beta,dbar\nP,0.95,0.80,0.030,0.010,0.05\n"
        "F,0.93,0.78,0.025,0.008,0.05\n")
    (DATA / "network_demand.csv").write_text(
        "region,base,growth\nR1,100.0,0.03\nR2,100.0,0.03\n")

sites_df = pd.read_csv(DATA / "network_sites.csv")
print(f"network_sites.csv: {len(sites_df)} rows x {len(sites_df.columns)} columns")
sites_df

network_sites.csv: 6 rows x 10 columns

,site,tier,home,cap_unit,lead,capex0,opex,legacy_units,legacy_vintage,legacy_retire
0,M1,M,R1,110,2,1800,1.2,2,-6,7
1,M2,M,R2,110,2,2000,1.4,2,-6,10
2,P1,P,R1,100,3,3300,2.0,2,-3,12
3,P2,P,R2,100,3,3100,2.2,2,-3,15
4,F1,F,R1,90,2,2900,2.5,2,-1,16
5,F2,F,R2,90,2,2700,2.3,2,-1,19

The other two tables. `network_tiers.csv` holds the yield-curve parameters for
the two tiers that have a *yield* to speak of — processing and fabrication.
Mining's yield is a single constant, so it is a knob, not a table.

In [3]:
tiers_df = pd.read_csv(DATA / "network_tiers.csv")
demand_df = pd.read_csv(DATA / "network_demand.csv")
print(f"network_tiers.csv: {len(tiers_df)} rows    "
      f"network_demand.csv: {len(demand_df)} rows")
display(tiers_df)
demand_df

network_tiers.csv: 2 rows    network_demand.csv: 2 rows

  tier  eta_bar  eta_0  alpha   beta  dbar
0    P     0.95   0.80  0.030  0.010  0.05
1    F     0.93   0.78  0.025  0.008  0.05

  region   base  growth
0     R1  110.0   0.025
1     R2   85.0   0.055

### 2.1 From table to lookup — see the key

A frame shows rows and columns. **The model does not index by row number.** Every
constraint below looks a value up by a key: `cap_unit['P1']`, `eta_bar['F']`,
`legacy['M1']`. Build the dictionaries and print them in the form the constraints
will use.

The index sets come out of the table itself, in file order — mines, then
processors, then fabricators — so the order the model iterates in is a property
of the data, not of a `sorted()` call somewhere.

In [4]:
REGIONS = list(dict.fromkeys(demand_df["region"]))
TIER = {r.site: r.tier for r in sites_df.itertuples()}
MINES = [s for s in TIER if TIER[s] == "M"]
PROCS = [s for s in TIER if TIER[s] == "P"]
FABS = [s for s in TIER if TIER[s] == "F"]
SITES = MINES + PROCS + FABS

HOME = {r.site: r.home for r in sites_df.itertuples()}
CAP_UNIT = {r.site: float(r.cap_unit) for r in sites_df.itertuples()}
LEAD = {r.site: int(r.lead) for r in sites_df.itertuples()}
CAPEX0 = {r.site: float(r.capex0) for r in sites_df.itertuples()}
OPEX = {r.site: float(r.opex) for r in sites_df.itertuples()}
LEGACY = {r.site: (int(r.legacy_units), int(r.legacy_vintage), int(r.legacy_retire))
          for r in sites_df.itertuples()}

print(f"index sets:  REGIONS = {REGIONS}")
print(f"             MINES   = {MINES}    PROCS = {PROCS}    FABS = {FABS}")
print(f"             SITES   = {SITES}   <- the order every loop below follows\n")
print(f"{'site':6s} {'tier':5s} {'home':5s} {'cap':>6s} {'lead':>5s} {'capex0':>8s}"
      f" {'opex':>6s}  legacy (units, vintage, retires)")
for s in SITES:
    print(f"{s:6s} {TIER[s]:5s} {HOME[s]:5s} {CAP_UNIT[s]:6.0f} {LEAD[s]:5d}"
          f" {CAPEX0[s]:8.0f} {OPEX[s]:6.2f}  {LEGACY[s]}")

index sets:  REGIONS = ['R1', 'R2']
             MINES   = ['M1', 'M2']    PROCS = ['P1', 'P2']    FABS = ['F1', 'F2']
             SITES   = ['M1', 'M2', 'P1', 'P2', 'F1', 'F2']   <- the order every loop below follows

site   tier  home     cap  lead   capex0   opex  legacy (units, vintage, retires)
M1     M     R1       110     2     1800   1.20  (2, -6, 7)
M2     M     R2       110     2     2000   1.40  (2, -6, 10)
P1     P     R1       100     3     3300   2.00  (2, -3, 12)
P2     P     R2       100     3     3100   2.20  (2, -3, 15)
F1     F     R1        90     2     2900   2.50  (2, -1, 16)
F2     F     R2        90     2     2700   2.30  (2, -1, 19)

The same move for the two single-key tables. Note the asymmetry in the demand
table: R2 starts smaller but grows more than twice as fast, so which region the
network should serve changes over the horizon. That is the whole reason the model
is multi-period.

In [5]:
ETA_BAR = {r.tier: float(r.eta_bar) for r in tiers_df.itertuples()}
ETA_0 = {r.tier: float(r.eta_0) for r in tiers_df.itertuples()}
ALPHA = {r.tier: float(r.alpha) for r in tiers_df.itertuples()}
BETA = {r.tier: float(r.beta) for r in tiers_df.itertuples()}
DBAR = {r.tier: float(r.dbar) for r in tiers_df.itertuples()}

DEMAND_BASE = {r.region: float(r.base) for r in demand_df.itertuples()}
DEMAND_GROWTH = {r.region: float(r.growth) for r in demand_df.itertuples()}

print("keyed by tier:")
for k in ETA_BAR:
    print(f"  {k!r}: ceiling {ETA_BAR[k]:.2f}  vintage-1 {ETA_0[k]:.2f}"
          f"  frontier/yr {ALPHA[k]:.3f}  within-life/yr {BETA[k]:.3f}"
          f"  max lifetime gain {DBAR[k]:.2f}")
print("\nkeyed by region:")
for g in REGIONS:
    print(f"  {g!r}: demand starts at {DEMAND_BASE[g]:6.1f}, "
          f"growing {100 * DEMAND_GROWTH[g]:.1f}% a year")

keyed by tier:
  'P': ceiling 0.95  vintage-1 0.80  frontier/yr 0.030  within-life/yr 0.010  max lifetime gain 0.05
  'F': ceiling 0.93  vintage-1 0.78  frontier/yr 0.025  within-life/yr 0.008  max lifetime gain 0.05

keyed by region:
  'R1': demand starts at  110.0, growing 2.5% a year
  'R2': demand starts at   85.0, growing 5.5% a year

### 2.2 Want to experiment? Change a number here, not in the CSV

Each table is now a dictionary keyed the way the model indexes. Assign to a key to
override one entry. The change flows into every model built below **and** into the
section 12 agreement check, because the package takes the data as an argument
instead of re-reading the file.

In [6]:
# ---------------------------------------------------------------------------
# Example - make the two processors equally expensive to build:
#
#     CAPEX0['P2'] = CAPEX0['P1']
#
# Uncomment, then re-run this cell and everything below it. P2's build-cost
# advantage disappears, the planner's siting choice shifts toward P1, and the
# section 12 assertion stays green because the notebook passes CAPEX0 to
# the package. Re-run with it commented out to get the shipped instance back.
# ---------------------------------------------------------------------------
print(f"CAPEX0['P1'] = {CAPEX0['P1']:.0f}, CAPEX0['P2'] = {CAPEX0['P2']:.0f}"
      f"   (P2 is {100 * (1 - CAPEX0['P2'] / CAPEX0['P1']):.0f}% cheaper today)")

CAPEX0['P1'] = 3300, CAPEX0['P2'] = 3100   (P2 is 6% cheaper today)

## 3. The knobs, and the structure derived from them

Everything in this section is **derived**: the horizon, discount factors, the
capital recovery factor, yields by vintage, the demand path, transport costs.
None of it is data and none of it is a knob — it is arithmetic on the two, and
doing that arithmetic is the point.

`lithium.core.build_core_structure` computes the same things, and section 12
is what proves the two derivations agree.

### 3.1 The horizon and the time value of money

`T` and `r` are the two knobs everything else in this section hangs off.

In [7]:
T = 20        # horizon, years
r = 0.05      # discount rate
LIFE = 20     # asset life, years
MAX_BUILDS = 3   # units that may be built at one site in one decision year

YEARS = list(range(1, T + 1))
DF = {t: 1.0 / (1 + r) ** t for t in YEARS}
CRF = r * (1 + r) ** LIFE / ((1 + r) ** LIFE - 1)

print(f"horizon {T} years at r = {r}")
print(f"CRF = {CRF:.6f}   (a 1.0 lump becomes {CRF:.4f} per year for {LIFE} years)")
print(f"discount factor: year 1 {DF[1]:.4f}, year {T} {DF[T]:.4f}"
      f"  -> the last year is worth {100 * DF[T]:.0f}% of the first")

horizon 20 years at r = 0.05
CRF = 0.080243   (a 1.0 lump becomes 0.0802 per year for 20 years)
discount factor: year 1 0.9524, year 20 0.3769  -> the last year is worth 38% of the first

### 3.2 Yields: a vintage effect and an ageing effect

Two things move an asset's yield, and they are not the same thing.

**The frontier improves.** An asset built later starts closer to the ceiling,
because the technology available in that year is better. That is `ALPHA`.

**An asset improves within its own life.** Operating experience lifts it toward
the ceiling too, at rate `BETA` — but by at most `DBAR` above where it started,
because a plant cannot be rebuilt by being run.

`ETA_MIN` clamps the arithmetic: a legacy asset from vintage −6 would otherwise
compute to something absurd.

**These curves never cross.** A later vintage starts higher and ages along a
parallel path, so it stays higher forever. That is worth checking rather than
assuming, and the cell asserts it.

In [8]:
ETA_MINE = 0.90    # ore -> concentrate; constant, so a knob rather than a table
ETA_MIN = 0.60     # clamp: legacy assets cannot be arbitrarily bad

VINTAGES = sorted({lv for (_, lv, _) in LEGACY.values()} | set(YEARS))
ETA = {}
for tier in ("P", "F"):
    eb, e0 = ETA_BAR[tier], ETA_0[tier]
    a, b, db = ALPHA[tier], BETA[tier], DBAR[tier]
    for v in VINTAGES:
        e_new = max(eb - (eb - e0) * (1 - a) ** (v - 1), ETA_MIN)
        for t in YEARS:
            e_t = eb - (eb - e_new) * (1 - b) ** (t - v)
            ETA[tier, v, t] = max(ETA_MIN, min(e_new + db, e_t))

assert all(ETA_MIN <= v <= 1.0 for v in ETA.values()), "a yield outside [ETA_MIN, 1]"
# a later vintage must stay above an earlier one, in every year both are running
assert all(ETA["P", 10, t] >= ETA["P", 2, t] for t in YEARS if t >= 10), \
    "vintage curves crossed - the frontier and ageing effects are mis-specified"

print(f"{len(ETA)} yields, keyed (tier, vintage, year)\n")
print(f"processing yield, by vintage and year:")
print(f"{'vintage':>8s} " + "".join(f"{'yr ' + str(t):>9s}" for t in (1, 5, 10, 15, 20)))
for v in (-3, 1, 5, 10, 15):
    print(f"{v:8d} " + "".join(f"{ETA['P', v, t]:9.4f}" if t >= max(v, 1) else f"{'-':>9s}"
                               for t in (1, 5, 10, 15, 20)))

920 yields, keyed (tier, vintage, year)

processing yield, by vintage and year:
 vintage      yr 1     yr 5    yr 10    yr 15    yr 20
      -3    0.7872   0.7937   0.8013   0.8086   0.8155
       1    0.8000   0.8059   0.8130   0.8197   0.8261
       5         -   0.8172   0.8237   0.8299   0.8358
      10         -        -   0.8360   0.8416   0.8469
      15         -        -        -   0.8521   0.8569

### 3.3 Demand, and the transport that makes geography matter

Demand grows from each region's base at its own rate. Transport is four times
dearer across regions than within one, and that single ratio is what stops the
planner simply building everything in whichever region is cheapest.

In [9]:
TRANSPORT_OWN, TRANSPORT_CROSS = 0.4, 1.6
SLACK_PEN = 45.0     # penalty per unit of demand left unmet

D = {(g, t): DEMAND_BASE[g] * (1 + DEMAND_GROWTH[g]) ** (t - 1)
     for g in REGIONS for t in YEARS}
TC = {(a, b): (TRANSPORT_OWN if HOME[a] == HOME[b] else TRANSPORT_CROSS)
      for a in SITES for b in SITES}
TC_DEM = {(f, g): (TRANSPORT_OWN if HOME[f] == g else TRANSPORT_CROSS)
          for f in FABS for g in REGIONS}

print(f"{'year':>5s} " + "".join(f"{g:>10s}" for g in REGIONS))
for t in (1, 5, 10, 15, 20):
    print(f"{t:5d} " + "".join(f"{D[g, t]:10.2f}" for g in REGIONS))
cross = [t for t in YEARS if D[REGIONS[1], t] > D[REGIONS[0], t]]
print(f"\n{REGIONS[1]} overtakes {REGIONS[0]} in year {min(cross)}"
      if cross else f"\n{REGIONS[1]} never overtakes {REGIONS[0]}")
print(f"transport: {TRANSPORT_OWN} within a region, {TRANSPORT_CROSS} across "
      f"({TRANSPORT_CROSS / TRANSPORT_OWN:.0f}x)")

 year         R1        R2
    1     110.00     85.00
    5     121.42    105.30
   10     137.37    137.62
   15     155.43    179.87
   20     175.85    235.08

R2 overtakes R1 in year 10
transport: 0.4 within a region, 1.6 across (4x)

### 3.4 The learning knobs

Capex splits in two: a **site adder** that never gets cheaper — land, permits,
connection — and a **technology** component that may. `LEARN_FRAC` is the share
that is technology, and only the processing and fabrication tiers learn, because
mining is mature.

`LR` is the learning rate: the fraction by which unit cost falls per doubling of
cumulative capacity. `Q0` is the incumbent cumulative capacity the curve starts
from, and `C_FLOOR_FRAC` stops it falling to zero.

In [10]:
LEARN_TIERS = ("P", "F")     # mining is mature; recovery technology learns
LEARN_SITES = [s for s in SITES if TIER[s] in LEARN_TIERS]
LEARN_FRAC = 0.70            # share of capex that is learnable technology
LR = 0.20                    # unit cost falls 20% per doubling of capacity
Q0 = 380.0                   # incumbent cumulative capacity
C_FLOOR_FRAC = 0.55          # floor, as a fraction of the starting unit cost
G_EXOG = 0.035               # exogenous capex decline per year, for that mode

print(f"learning sites: {LEARN_SITES}   (mining excluded)")
print(f"of each site's capex0, {100 * LEARN_FRAC:.0f}% is technology that can "
      f"learn and {100 * (1 - LEARN_FRAC):.0f}% is a site adder that cannot")
print(f"learning rate {100 * LR:.0f}% per doubling, floored at "
      f"{100 * C_FLOOR_FRAC:.0f}% of the starting cost")

learning sites: ['P1', 'P2', 'F1', 'F2']   (mining excluded)
of each site's capex0, 70% is technology that can learn and 30% is a site adder that cannot
learning rate 20% per doubling, floored at 55% of the starting cost

## 4. Charging capex: the coefficient that decides everything

A facility decided in year $v$ comes online in year $v + \text{lead}_s$ and runs
for `LIFE` years. How much of its cost belongs inside a twenty-year horizon?

Two defensible answers, and they are not close.

**Lump sum.** Pay the whole cost at the decision year, discounted:
$\pi_{s,v} = \delta_v$. Simple, and it charges the model for an asset most of
whose life falls *outside* the horizon.

**Annualised.** Spread the cost over the asset's life with the capital recovery
factor, and charge only the years that fall inside the horizon:
$\pi_{s,v} = \text{CRF}\sum_{t=v+\text{lead}}^{\min(v+\text{lead}+L-1,\,T)}\delta_t$.

The difference is not cosmetic and it is not small — section 8 measures it. Write
the multiplier out for both modes and look at what happens late in the horizon.

In [11]:
CAPEX_MODES = ("annualized", "lumpsum")

PI = {}
for mode in CAPEX_MODES:
    for s in SITES:
        for v in YEARS:
            online = v + LEAD[s]
            if mode == "lumpsum":
                PI[mode, s, v] = DF.get(v, 0.0)
            else:
                last = min(online + LIFE - 1, T)
                PI[mode, s, v] = (0.0 if last < online else
                                  CRF * sum(DF[t] for t in range(online, last + 1)
                                            if t in DF))

print(f"PV of $1 of capex at site P1 (lead {LEAD['P1']} yrs), by decision year:")
print(f"{'year':>5s} {'annualized':>12s} {'lumpsum':>10s} {'ratio':>8s}")
for v in (1, 5, 10, 15, 18, 20):
    a, l = PI["annualized", "P1", v], PI["lumpsum", "P1", v]
    print(f"{v:5d} {a:12.4f} {l:10.4f} {a / l if l else float('nan'):8.2f}")

PV of $1 of capex at site P1 (lead 3 yrs), by decision year:
 year   annualized    lumpsum    ratio
    1       0.7815     0.9524     0.82
    5       0.5357     0.7835     0.68
   10       0.2888     0.6139     0.47
   15       0.0953     0.4810     0.20
   18       0.0000     0.4155     0.00
   20       0.0000     0.3769     0.00

Read the last two rows. By year 18 the annualised multiplier has collapsed —
a processor decided then comes online in year 21, which is **outside the
horizon**, so it is charged nothing and delivers nothing. The lump-sum
multiplier has not collapsed at all: it still charges 41% of the cost, for an
asset the model will never operate.

That asymmetry is the whole of section 8. Lump-sum does not merely cost more —
it **systematically refuses to build late**, and calls that economics.

> **Predict before you run.** Given that, which mode do you expect to leave more
> demand unmet? And by roughly how much — a few per cent, or more?

## 5. The learning curve, and why SOS2 is mandatory

Capex splits in two: a **site adder** that never gets cheaper, and a
**technology** component that may. Under Wright's law the unit cost of the
technology falls by `LR` per doubling of cumulative capacity $Q$:

$$c(Q) \;=\; \max\Big(c_{\text{floor}},\; (Q/Q_0)^{-b}\Big),
\qquad b = -\log_2(1 - \text{LR})$$

**The model needs the area under that curve, not the curve itself.** Going from
$Q_0$ to $Q$ costs the integral of $c$, because the 401st unit costs what the
curve says at 401 — not what it said at $Q_0$. So integrate numerically and let
the model interpolate between breakpoints.

**And here is the trap.** Cumulative cost $C(Q)$ is **concave**, and it enters a
cost we are **minimising**. A chord between two breakpoints therefore lies
*below* the true curve, so a free convex combination would happily mix
breakpoint 0 with breakpoint 6 and claim a discount that does not exist.
**SOS2** restricts the weights to at most two *adjacent* breakpoints, which is
the interpolation we actually meant.

Without it the model does not fail — it returns a cheaper, wrong answer. That is
the worst kind of bug, and section 10 is where it would have shown up.

In [12]:
import math

INVEST_YEARS = list(range(1, T + 1, 3))   # section 9 sweeps this; section 6 uses it
NBP = 7          # breakpoints on the cumulative-cost curve
PANELS = 400     # trapezoid panels per breakpoint

# The mesh has to reach as far as cumulative capacity can plausibly go, and that
# depends on how many INVESTMENT years there are - not how many years there are.
QMAX = Q0 + sum(CAP_UNIT[s] * MAX_BUILDS for s in LEARN_SITES) * max(
    1, len(INVEST_YEARS) // 3)
_b = -math.log2(1 - LR)

QBP = [Q0 + (QMAX - Q0) * (i / (NBP - 1)) for i in range(NBP)]
CBP = []
for q in QBP:
    if q <= Q0:
        CBP.append(0.0)
        continue
    h = (q - Q0) / PANELS
    grid = [Q0 + i * h for i in range(PANELS + 1)]
    unit = [max(C_FLOOR_FRAC, (g / Q0) ** (-_b)) for g in grid]
    CBP.append(sum(0.5 * (unit[i] + unit[i + 1]) * h for i in range(PANELS)))

print(f"learning exponent b = {_b:.4f}   (unit cost x2^-b per doubling)")
print(f"{'k':>2s} {'Q (cum capacity)':>18s} {'unit cost':>11s} {'C (cum spend)':>15s}")
for k in range(NBP):
    print(f"{k:2d} {QBP[k]:18.1f} "
          f"{max(C_FLOOR_FRAC, (QBP[k] / Q0) ** (-_b)):11.4f} {CBP[k]:15.2f}")

# the property that makes SOS2 necessary: the chord lies BELOW the curve
mid_chord = 0.5 * (CBP[0] + CBP[-1])
mid_true = CBP[NBP // 2]
assert mid_chord < mid_true, "C(Q) is not concave; the SOS2 argument does not apply"
print(f"\nchord midpoint {mid_chord:.2f} < true midpoint {mid_true:.2f}")
print("-> a free convex combination would understate cost. Hence SOS2.")

learning exponent b = 0.3219   (unit cost x2^-b per doubling)
 k   Q (cum capacity)   unit cost   C (cum spend)
 0              380.0      1.0000            0.00
 1              760.0      0.8000          336.25
 2             1140.0      0.7021          619.99
 3             1520.0      0.6400          874.24
 4             1900.0      0.5956         1108.60
 5             2280.0      0.5617         1328.23
 6             2660.0      0.5500         1538.12

chord midpoint 769.06 < true midpoint 874.24
-> a free convex combination would understate cost. Hence SOS2.

## 6. The model, built by hand

The next seven cells build the whole thing, one block at a time, in its simplest
form: the full horizon, no learning, and no rolling-horizon machinery. Sections 8
to 11 turn those options on one at a time, with the narration for each where it
is used.

### 6.1 The build decisions, and a symmetry that costs nothing to break

$y_{s,v,k}$ is the $k$-th unit at site $s$ decided in year $v$. The units at one
site in one year are **interchangeable**, so a solver exploring
$(1,0,0)$ and $(0,1,0)$ and $(0,0,1)$ is exploring the same plan three times.
Insisting they are taken in order — $y_{s,v,0}\ge y_{s,v,1}\ge y_{s,v,2}$ —
removes that without removing a single distinct solution.

`INVEST_YEARS` is a knob and section 9 is about it. A decision is only kept if
the asset comes online inside the horizon: deciding in year 19 to build a
processor with a 3-year lead is a decision to build nothing.

In [13]:
# 1e-3, not the 0.005 this model was written with. At 0.005 the
# lumpsum/endogenous case stops 0.07% above its true optimum, which is
# enough to break section 12's agreement assertion. See 12.1.
MIPGAP = 1e-3

m = gp.Model("deterministic")
m.Params.OutputFlag = 0
m.Params.MIPGap = MIPGAP

# a decision only matters if the asset comes online inside the horizon
SITE_IY = {s: [v for v in INVEST_YEARS if v + LEAD[s] <= T] for s in SITES}

y = {}
for s in SITES:
    for v in SITE_IY[s]:
        for k in range(MAX_BUILDS):
            y[s, v, k] = m.addVar(vtype=GRB.BINARY, ub=1.0, name=f"y_{s}_{v}_{k}")
# symmetry breaking: units at a site-year are interchangeable
for s in SITES:
    for v in SITE_IY[s]:
        for k in range(MAX_BUILDS - 1):
            m.addConstr(y[s, v, k] >= y[s, v, k + 1])

m.update()
print(f"investment years: {INVEST_YEARS}")
for s in SITES:
    dropped = set(INVEST_YEARS) - set(SITE_IY[s])
    print(f"  {s}: lead {LEAD[s]}, usable decision years {SITE_IY[s]}"
          + (f"   (dropped {sorted(dropped)})" if dropped else ""))
print(f"\n{m.NumVars} binaries, {m.NumConstrs} symmetry-breaking constraints")

Restricted license - for non-production use only - expires 2027-11-29

investment years: [1, 4, 7, 10, 13, 16, 19]
  M1: lead 2, usable decision years [1, 4, 7, 10, 13, 16]   (dropped [19])
  M2: lead 2, usable decision years [1, 4, 7, 10, 13, 16]   (dropped [19])
  P1: lead 3, usable decision years [1, 4, 7, 10, 13, 16]   (dropped [19])
  P2: lead 3, usable decision years [1, 4, 7, 10, 13, 16]   (dropped [19])
  F1: lead 2, usable decision years [1, 4, 7, 10, 13, 16]   (dropped [19])
  F2: lead 2, usable decision years [1, 4, 7, 10, 13, 16]   (dropped [19])

108 binaries, 72 symmetry-breaking constraints

### 6.2 What is running in year *t*

A site's capacity in year $t$ comes from three places: the **legacy** units it
started with, which retire on a fixed schedule, and any units **decided** in an
earlier year whose lead time has elapsed and whose life has not.

Building this as a dictionary rather than a function keeps it readable and keeps
the vintage attached: the model needs to know not just *how much* capacity is
running but *which vintage*, because yield depends on it.

In [14]:
ONLINE = {}
for s in SITES:
    for t in YEARS:
        terms = []
        ln, lv, lret = LEGACY[s]
        if t <= lret:                       # legacy units, until they retire
            terms.append((lv, float(ln)))
        for v in SITE_IY[s]:                # units decided earlier, if online and alive
            on = v + LEAD[s]
            if on <= t <= on + LIFE - 1:
                terms.append((v, gp.quicksum(y[s, v, k] for k in range(MAX_BUILDS))))
        ONLINE[s, t] = terms

print(f"vintages available at P1, year by year:")
for t in (1, 5, 10, 13, 16, 20):
    vs = [v for (v, _) in ONLINE["P1", t]]
    print(f"  year {t:2d}: {vs}"
          + ("   <- legacy retired" if LEGACY['P1'][2] < t else ""))

vintages available at P1, year by year:
  year  1: [-3]
  year  5: [-3, 1]
  year 10: [-3, 1, 4, 7]
  year 13: [1, 4, 7, 10]   <- legacy retired
  year 16: [1, 4, 7, 10, 13]   <- legacy retired
  year 20: [1, 4, 7, 10, 13, 16]   <- legacy retired

### 6.3 Throughput and the arcs between sites

Throughput at a processor or fabricator is indexed **by vintage**, because a
vintage-2 asset and a vintage-13 asset in the same year have different yields and
the model must be able to tell them apart. Mines are not: their yield is a
constant.

Then the arcs: mine → processor, processor → fabricator, fabricator → region, and
a slack variable for demand nobody serves.

In [15]:
thr = {}
for s in PROCS + FABS:
    for t in YEARS:
        for (v, _) in ONLINE[s, t]:
            if (s, v, t) not in thr:
                thr[s, v, t] = m.addVar(name=f"thr_{s}_{v}_{t}")
ext = {(s, t): m.addVar(name=f"ext_{s}_{t}") for s in MINES for t in YEARS}

fmp = {(a, b, t): m.addVar() for a in MINES for b in PROCS for t in YEARS}
fpf = {(a, b, t): m.addVar() for a in PROCS for b in FABS for t in YEARS}
ffr = {(a, g, t): m.addVar() for a in FABS for g in REGIONS for t in YEARS}
slk = {(g, t): m.addVar() for g in REGIONS for t in YEARS}

m.update()
print(f"{len(thr):5d} vintage-indexed throughput variables")
print(f"{len(ext):5d} mine extraction variables")
print(f"{len(fmp) + len(fpf) + len(ffr):5d} arc flows"
      f"   ({len(fmp)} mine->proc, {len(fpf)} proc->fab, {len(ffr)} fab->region)")
print(f"{len(slk):5d} unmet-demand variables")
print(f"{m.NumVars:5d} variables in total")

  302 vintage-indexed throughput variables
   40 mine extraction variables
  240 arc flows   (80 mine->proc, 80 proc->fab, 80 fab->region)
   40 unmet-demand variables
  730 variables in total

### 6.4 Capacity: you cannot run what you did not build

Two shapes, and the difference matters. A mine's extraction is capped by its
**total** online capacity — one number. A processor's or fabricator's throughput
is capped **per vintage**, because throughput is tracked per vintage.

In [16]:
for t in YEARS:
    for s in MINES:
        cap = gp.quicksum(n * CAP_UNIT[s] for (_, n) in ONLINE[s, t])
        m.addConstr(ext[s, t] <= cap)
    for s in PROCS + FABS:
        for (v, n) in ONLINE[s, t]:
            m.addConstr(thr[s, v, t] <= n * CAP_UNIT[s])

m.update()
print(f"{m.NumConstrs} constraints after the capacity block")

414 constraints after the capacity block

### 6.5 Flow balance: what comes out of one tier goes into the next

Four equalities per year, and they are the physical heart of the model.

Ore extracted, times the mining yield, equals what flows to processing. What
flows in equals what processing takes in. What processing *puts out* — its
throughput times a **vintage-dependent** yield — equals what flows to
fabrication. And so on to the regions, where deliveries plus unmet demand must
cover what is demanded.

Note where `ETA` enters: on the **output** side of a tier, never the input. A
tonne fed into an old processor comes out smaller than a tonne fed into a new one.

In [17]:
for t in YEARS:
    for s in MINES:
        m.addConstr(ETA_MINE * ext[s, t] == gp.quicksum(fmp[s, b, t] for b in PROCS))
    for s in PROCS:
        vints = [v for (v, _) in ONLINE[s, t]]
        m.addConstr(gp.quicksum(fmp[a, s, t] for a in MINES)
                    == gp.quicksum(thr[s, v, t] for v in vints))
        m.addConstr(gp.quicksum(ETA["P", v, t] * thr[s, v, t] for v in vints)
                    == gp.quicksum(fpf[s, b, t] for b in FABS))
    for s in FABS:
        vints = [v for (v, _) in ONLINE[s, t]]
        m.addConstr(gp.quicksum(fpf[a, s, t] for a in PROCS)
                    == gp.quicksum(thr[s, v, t] for v in vints))
        m.addConstr(gp.quicksum(ETA["F", v, t] * thr[s, v, t] for v in vints)
                    == gp.quicksum(ffr[s, g, t] for g in REGIONS))
    for g in REGIONS:
        m.addConstr(gp.quicksum(ffr[f, g, t] for f in FABS) + slk[g, t] >= D[g, t])

m.update()
print(f"{m.NumConstrs} constraints after the flow balance")
print(f"({len(YEARS)} years x ({len(MINES)} mines + 2x{len(PROCS)} procs"
      f" + 2x{len(FABS)} fabs + {len(REGIONS)} regions) added)")

654 constraints after the flow balance
(20 years x (2 mines + 2x2 procs + 2x2 fabs + 2 regions) added)

### 6.6 The capex term

The site adder is charged in every mode. The technology component is charged at a
flat rate here, because this first build uses `learning='none'` — section 10 is
where the other two modes arrive, and where the SOS2 block from section 5 gets
built.

`TECH_RATE` is the average technology cost per unit of capacity across the
learning sites, which is what makes a single learning curve meaningful for
several sites at once.

In [18]:
LS = set(LEARN_SITES)
ADDER = {s: CAPEX0[s] * (1 - LEARN_FRAC) if s in LS else CAPEX0[s] for s in SITES}
TECH_RATE = sum(CAPEX0[s] * LEARN_FRAC / CAP_UNIT[s] for s in LS) / len(LS)

CAPEX_MODE = "annualized"     # section 8 is about this choice

capex = gp.LinExpr()
for s in SITES:                                    # site adders, every mode
    for v in SITE_IY[s]:
        for k in range(MAX_BUILDS):
            capex += PI[CAPEX_MODE, s, v] * ADDER[s] * y[s, v, k]
for s in LEARN_SITES:                              # technology, flat for 'none'
    for v in SITE_IY[s]:
        for k in range(MAX_BUILDS):
            capex += PI[CAPEX_MODE, s, v] * TECH_RATE * CAP_UNIT[s] * y[s, v, k]

print(f"technology rate {TECH_RATE:.3f} per unit of capacity")
print(f"{'site':6s} {'capex0':>8s} {'site adder':>11s} {'technology':>11s}")
for s in SITES:
    tech = TECH_RATE * CAP_UNIT[s] if s in LS else 0.0
    print(f"{s:6s} {CAPEX0[s]:8.0f} {ADDER[s]:11.1f} {tech:11.1f}"
          + ("" if s in LS else "   <- mining does not learn"))
print(f"\ncapex expression: {capex.size()} linear terms")

technology rate 22.089 per unit of capacity
site     capex0  site adder  technology
M1         1800      1800.0         0.0   <- mining does not learn
M2         2000      2000.0         0.0   <- mining does not learn
P1         3300       990.0      2208.9
P2         3100       930.0      2208.9
F1         2900       870.0      1988.0
F2         2700       810.0      1988.0

capex expression: 180 linear terms

### 6.7 Operating cost, transport, the penalty — and solve

Everything here is an annual flow, so every term carries the discount factor
`DF[t]`. The capex terms above carried `PI` instead, because they are annuities
on a lump rather than flows.

> **Predict before you run.** Demand over the twenty years totals about 5,774
> units, and the penalty for leaving a unit unserved is 45 against an operating
> cost near 6. Will the model serve everything?

In [19]:
op = gp.LinExpr()
for t in YEARS:
    w = DF[t]
    for s in MINES:
        op += w * OPEX[s] * ext[s, t]
    for s in PROCS + FABS:
        for (v, _) in ONLINE[s, t]:
            op += w * OPEX[s] * thr[s, v, t]
    for a in MINES:
        for b in PROCS:
            op += w * TC[a, b] * fmp[a, b, t]
    for a in PROCS:
        for b in FABS:
            op += w * TC[a, b] * fpf[a, b, t]
    for f in FABS:
        for g in REGIONS:
            op += w * TC_DEM[f, g] * ffr[f, g, t]
    for g in REGIONS:
        op += w * SLACK_PEN * slk[g, t]

m.setObjective(capex + op, GRB.MINIMIZE)
m.update()
assert m.NumVars > 0 and m.NumConstrs > 0, "empty model"
assert m.NumSOS == 0, "learning='none' should add no SOS2 sets"

m.optimize()
assert m.SolCount > 0, f"no solution; status {m.Status}"

hand_built = m.ObjVal
plan = {}
for (s, v, k), var in y.items():
    if var.X > 0.5:
        plan[s, v] = plan.get((s, v), 0) + 1
print(f"status {m.Status}, objective {hand_built:,.1f}, gap {m.MIPGap:.2e}")
print(f"  capex          {capex.getValue():12,.1f}")
print(f"  operating etc  {op.getValue():12,.1f}")
print(f"  units built    {sum(plan.values()):12d}")
print(f"  unmet demand   {sum(v.X for v in slk.values()):12,.2f}"
      f"   of {sum(D.values()):,.0f} demanded")
print(f"\nplan: {dict(sorted(plan.items()))}")

status 2, objective 47,885.9, gap 0.00e+00
  capex              13,270.9
  operating etc      34,615.0
  units built              18
  unmet demand          23.71   of 5,774 demanded

plan: {('F1', 10): 1, ('F1', 13): 1, ('F1', 16): 1, ('F2', 13): 1, ('F2', 16): 2, ('M1', 4): 2, ('M1', 7): 1, ('M2', 7): 2, ('M2', 13): 1, ('P1', 7): 1, ('P1', 10): 2, ('P2', 13): 3}

## 7. Now the streamlined version

**This is where the notebook crosses from learning into convenience.**

You have written the model once. Sections 8 to 11 need it **about thirty times** —
two capex modes, four investment meshes, three learning modes, five foresight
windows, and a rolling horizon that rebuilds it on every roll.

So the next cell wraps it, with the options those sections need: the capex mode,
the learning mode, an operating window, and the rolling-horizon machinery. Each
option is narrated in the section that uses it, not here.

Then cell 7.1 **proves the wrapper reproduces what you built**.

In [20]:
def build(invest_years, capex_mode="annualized", learning="none",
          y_start=1, y_end=None, fixed_builds=None, forced_zero_after=None,
          relax_int_after=None, mipgap=MIPGAP):
    """Sections 6.1-6.7, plus the options sections 8-11 turn on."""
    y_end = y_end or T
    yrs = [t for t in YEARS if y_start <= t <= y_end]
    IY = [v for v in invest_years if y_start <= v <= y_end]
    if forced_zero_after is not None:
        IY = [v for v in IY if v <= forced_zero_after]
    site_iy = {s: [v for v in IY if v + LEAD[s] <= y_end] for s in SITES}
    prebuilt = fixed_builds or {}

    mm = gp.Model()
    mm.Params.OutputFlag = 0
    mm.Params.MIPGap = mipgap

    yy = {}
    for s in SITES:
        for v in site_iy[s]:
            for k in range(MAX_BUILDS):
                cont = relax_int_after is not None and v > relax_int_after
                yy[s, v, k] = mm.addVar(
                    vtype=GRB.CONTINUOUS if cont else GRB.BINARY, ub=1.0)
    for s in SITES:
        for v in site_iy[s]:
            for k in range(MAX_BUILDS - 1):
                mm.addConstr(yy[s, v, k] >= yy[s, v, k + 1])

    online = {}
    for s in SITES:
        for t in yrs:
            terms = []
            ln, lv, lret = LEGACY[s]
            if t <= lret:
                terms.append((lv, float(ln)))
            for v in site_iy[s]:
                on = v + LEAD[s]
                if on <= t <= on + LIFE - 1:
                    terms.append((v, gp.quicksum(yy[s, v, k]
                                                 for k in range(MAX_BUILDS))))
            for (ps, pv), n in prebuilt.items():
                if ps == s and pv + LEAD[s] <= t <= pv + LEAD[s] + LIFE - 1:
                    terms.append((pv, n))
            online[s, t] = terms

    th, ex = {}, {}
    for s in PROCS + FABS:
        for t in yrs:
            for (v, _) in online[s, t]:
                if (s, v, t) not in th:
                    th[s, v, t] = mm.addVar()
    for s in MINES:
        for t in yrs:
            ex[s, t] = mm.addVar()
    a_mp = {(a, b, t): mm.addVar() for a in MINES for b in PROCS for t in yrs}
    a_pf = {(a, b, t): mm.addVar() for a in PROCS for b in FABS for t in yrs}
    a_fr = {(a, g, t): mm.addVar() for a in FABS for g in REGIONS for t in yrs}
    sl = {(g, t): mm.addVar() for g in REGIONS for t in yrs}

    # capacity first, then flow balance - the SAME order as section 6, so the
    # two models are not merely equivalent but identically presented. At a 0.5%
    # gap a different presentation can land on a different incumbent, and the
    # 7.1 check would then fail for no reason worth chasing.
    for t in yrs:
        for s in MINES:
            mm.addConstr(ex[s, t] <= gp.quicksum(n * CAP_UNIT[s]
                                                 for (_, n) in online[s, t]))
        for s in PROCS + FABS:
            for (v, n) in online[s, t]:
                mm.addConstr(th[s, v, t] <= n * CAP_UNIT[s])
    for t in yrs:
        for s in MINES:
            mm.addConstr(ETA_MINE * ex[s, t]
                         == gp.quicksum(a_mp[s, b, t] for b in PROCS))
        for s in PROCS:
            vi = [v for (v, _) in online[s, t]]
            mm.addConstr(gp.quicksum(a_mp[a, s, t] for a in MINES)
                         == gp.quicksum(th[s, v, t] for v in vi))
            mm.addConstr(gp.quicksum(ETA["P", v, t] * th[s, v, t] for v in vi)
                         == gp.quicksum(a_pf[s, b, t] for b in FABS))
        for s in FABS:
            vi = [v for (v, _) in online[s, t]]
            mm.addConstr(gp.quicksum(a_pf[a, s, t] for a in PROCS)
                         == gp.quicksum(th[s, v, t] for v in vi))
            mm.addConstr(gp.quicksum(ETA["F", v, t] * th[s, v, t] for v in vi)
                         == gp.quicksum(a_fr[s, g, t] for g in REGIONS))
        for g in REGIONS:
            mm.addConstr(gp.quicksum(a_fr[f, g, t] for f in FABS) + sl[g, t]
                         >= D[g, t])

    cx = gp.LinExpr()
    for s in SITES:
        for v in site_iy[s]:
            pi = (DF.get(v, 0.0) if capex_mode == "lumpsum" else
                  (0.0 if min(v + LEAD[s] + LIFE - 1, y_end) < v + LEAD[s] else
                   CRF * sum(DF[t] for t in range(v + LEAD[s],
                                                  min(v + LEAD[s] + LIFE - 1,
                                                      y_end) + 1) if t in DF)))
            for k in range(MAX_BUILDS):
                cx += pi * ADDER[s] * yy[s, v, k]
            if s in LS and learning in ("none", "exogenous"):
                decay = (1 - G_EXOG) ** (v - 1) if learning == "exogenous" else 1.0
                rate = TECH_RATE * max(decay, C_FLOOR_FRAC)
                for k in range(MAX_BUILDS):
                    cx += pi * rate * CAP_UNIT[s] * yy[s, v, k]

    if learning == "endogenous":
        prevC = None
        for v in sorted({v for s in LS for v in site_iy[s]}):
            Qv = mm.addVar(lb=Q0, ub=QMAX)
            Cv = mm.addVar(lb=0)
            lam = [mm.addVar(lb=0, ub=1) for _ in QBP]
            mm.addConstr(gp.quicksum(lam) == 1)
            mm.addConstr(Qv == gp.quicksum(l * q for l, q in zip(lam, QBP)))
            mm.addConstr(Cv == gp.quicksum(l * c for l, c in zip(lam, CBP)))
            mm.addSOS(GRB.SOS_TYPE2, lam)              # <-- section 5's restriction
            pre = sum(CAP_UNIT[ps] * n for (ps, pv), n in prebuilt.items()
                      if ps in LS and pv <= v)
            mm.addConstr(Qv == Q0 + pre + gp.quicksum(
                CAP_UNIT[s] * yy[s, vv, k] for s in LS for vv in site_iy[s]
                if vv <= v for k in range(MAX_BUILDS)))
            cand = [(DF.get(v, 0.0) if capex_mode == "lumpsum" else
                     CRF * sum(DF[t] for t in range(v + LEAD[s],
                                                    min(v + LEAD[s] + LIFE - 1,
                                                        y_end) + 1) if t in DF))
                    for s in LS if v in site_iy[s]]
            pi = sum(cand) / len(cand) if cand else 0.0
            cx += pi * TECH_RATE * (Cv - (prevC if prevC is not None else 0))
            prevC = Cv

    ope = gp.LinExpr()
    for t in yrs:
        w = DF[t]
        for s in MINES:
            ope += w * OPEX[s] * ex[s, t]
        for s in PROCS + FABS:
            for (v, _) in online[s, t]:
                ope += w * OPEX[s] * th[s, v, t]
        for a in MINES:
            for b in PROCS:
                ope += w * TC[a, b] * a_mp[a, b, t]
        for a in PROCS:
            for b in FABS:
                ope += w * TC[a, b] * a_pf[a, b, t]
        for f in FABS:
            for g in REGIONS:
                ope += w * TC_DEM[f, g] * a_fr[f, g, t]
        for g in REGIONS:
            ope += w * SLACK_PEN * sl[g, t]

    mm.setObjective(cx + ope, GRB.MINIMIZE)
    mm._y, mm._slk = yy, sl
    return mm


def plan_of(mm):
    """{(site, decision year): units} from a solved model."""
    out = {}
    for (s, v, k), var in mm._y.items():
        if var.X > 0.5:
            out[s, v] = out.get((s, v), 0) + 1
    return out


print("build() and plan_of() defined")

build() and plan_of() defined

### 7.1 Does the wrapper reproduce the hand-built model?

In [21]:
check = build(INVEST_YEARS, capex_mode="annualized", learning="none")
check.optimize()
rel = abs(check.ObjVal - hand_built) / abs(hand_built)
print(f"hand-built (section 6.7): {hand_built:,.9f}")
print(f"wrapper    (section 7)  : {check.ObjVal:,.9f}")
assert rel < 1e-9, f"the wrapper is not the model you read; relative gap {rel:.2e}"
assert plan_of(check) == plan, "same objective, different plan - check the symmetry break"
print(f"\nagree to {rel:.1e}, and the build plans match - the wrap is earned")

hand-built (section 6.7): 47,885.858650728
wrapper    (section 7)  : 47,885.858650728

agree to 0.0e+00, and the build plans match - the wrap is earned

## 8. Lump-sum versus annualised capex

In [22]:
rows = []
for mode in CAPEX_MODES:
    mm = build(INVEST_YEARS, capex_mode=mode, learning="none")
    mm.optimize()
    assert mm.SolCount > 0, f"{mode} found no solution"
    pl = plan_of(mm)
    rows.append(dict(capex_mode=mode, objective=round(mm.ObjVal, 1),
                     units_built=sum(pl.values()),
                     last_decision_year=max(v for (_, v) in pl),
                     unmet_demand=round(sum(v.X for v in mm._slk.values()), 2)))
capex_table = pd.DataFrame(rows)

a, l = capex_table.iloc[0], capex_table.iloc[1]
assert l.objective > a.objective, "lump-sum should charge more inside the horizon"
assert l.unmet_demand > a.unmet_demand, "and should therefore serve less"
print(f"lump-sum costs {100 * (l.objective / a.objective - 1):+.1f}% and leaves "
      f"{l.unmet_demand / a.unmet_demand:.1f}x more demand unmet")
print(f"latest build decision: annualised year {a.last_decision_year}, "
      f"lump-sum year {l.last_decision_year} "
      f"(investment years are {INVEST_YEARS})")
capex_table

lump-sum costs +26.4% and leaves 14.4x more demand unmet
latest build decision: annualised year 16, lump-sum year 13 (investment years are [1, 4, 7, 10, 13, 16, 19])

   capex_mode  objective  units_built  last_decision_year  unmet_demand
0  annualized    47885.9           18                  16         23.71
1     lumpsum    60526.4           13                  13        342.38

**Lump-sum abandons the end of the horizon.** Its last build decision is year 13,
against annualised's year 16 — it walks away from two of the seven investment
opportunities. And it leaves **342.4 units of demand unmet against 23.7**, 14.4
times more, while costing 26.4% more overall.

That is not economics. It is an accounting artefact of **truncating the horizon
while charging the full asset cost**: a facility decided in year 13 runs for
twenty years, of which the model sees seven, but lump-sum bills it for all twenty.
Annualised bills it for the seven it sees.

Two caveats for a real model. Use the **same $r$** in the CRF as in the objective,
or you reintroduce a wedge by the back door. And **lock the capital charge at the
vintage's cost** — do not let it float down as later learning occurs, or an asset
gets cheaper after it is built.

One honest counter-caveat: annualising removes the anti-late-build bias so
completely that you will see builds right at the horizon edge. That is correct if
capacity can effectively be rented, but if it is lumpy and irreversible you want
an explicit salvage term, or a **cool-down buffer** — model to year 30, report to
year 20.

## 9. How finely should investment be discretised?

Every investment year multiplies the binary count by the number of sites times
`MAX_BUILDS`. Fewer years means a smaller, faster model — and a coarser answer.

> **Predict before you run.** Four meshes: every year, a staggered mesh (annual
> early, coarse late), every third year, every fifth. Rank them by objective
> before you look. Does more investment years always mean a better answer?

In [23]:
import time

MESHES = [("annual", list(range(1, T + 1))),
          ("staggered", [1, 2, 3, 4, 5, 6, 7, 9, 11, 16]),
          ("every 3rd", list(range(1, T + 1, 3))),
          ("every 5th", list(range(1, T + 1, 5)))]

rows = []
for name, iy in MESHES:
    t0 = time.time()
    mm = build(iy, capex_mode="annualized", learning="none")
    mm.optimize()
    assert mm.SolCount > 0, f"{name} found no solution"
    rows.append(dict(mesh=name, invest_years=len(iy), objective=round(mm.ObjVal, 1),
                     binaries=mm.NumBinVars, variables=mm.NumVars,
                     seconds=round(time.time() - t0, 1)))
mesh_table = pd.DataFrame(rows)

best = mesh_table.loc[mesh_table.objective.idxmin()]
print(f"best objective: {best.mesh} at {best.objective:,.1f} "
      f"with {best.invest_years} investment years and {best.binaries} binaries")
stag = mesh_table[mesh_table.mesh == "staggered"].iloc[0]
e3 = mesh_table[mesh_table.mesh == "every 3rd"].iloc[0]
print(f"but 'staggered' has {stag.invest_years} years and {stag.binaries} binaries "
      f"and scores {stag.objective:,.1f},")
print(f"while 'every 3rd' has {e3.invest_years} years and {e3.binaries} binaries "
      f"and scores {e3.objective:,.1f} - BETTER with fewer of both.")
mesh_table

best objective: annual at 46,311.3 with 20 investment years and 318 binaries
but 'staggered' has 10 years and 180 binaries and scores 48,539.7,
while 'every 3rd' has 7 years and 108 binaries and scores 47,885.9 - BETTER with fewer of both.

        mesh  invest_years  objective  binaries  variables  seconds
0     annual            20    46311.3       318       1348     11.3
1  staggered            10    48539.7       180       1046      4.3
2  every 3rd             7    47885.9       108        730      0.6
3  every 5th             4    50180.8        72        614      0.3

**More investment years is not better.** The staggered mesh has 10 investment
years and 180 binaries; every-third has 7 and 108, and scores **1.3% lower**
(47,885.9 against 48,539.7). Fewer decisions, fewer binaries, and a better
answer.

The reason is that the meshes are **not nested**. Staggered runs annually through
year 7 and then jumps to 9, 11, 16; every-third reaches 19. Staggered spends its
resolution early, where the legacy fleet has not yet retired and there is little
to decide, and has none left for the late-horizon replacement wave. Placement
beats count — which is the same lesson as the revenue mesh in Part 4c-exact, one
model family over.

That is a correction to what this notebook used to say. It claimed the staggered
mesh "buys most of the speedup of uniform 5-year periods at a fraction of the
accuracy cost, because it puts binaries where decisions actually bind". The first
half is true — staggered does beat every-fifth, 48,539.7 against 50,180.8. The
explanation is not: on this instance the binaries are *not* where decisions bind,
and a uniform every-third mesh with fewer binaries beats it.

**The practical rule is therefore weaker and more honest than "stagger it":**
sweep the mesh, and do not assume a cleverly-shaped one dominates a uniform one.
The annual mesh is the reference at 46,311.3, and every coarser mesh pays
something against it — 3.4% for every-third, 4.8% for staggered, 8.4% for
every-fifth. Note that ordering: the *uniform* coarse mesh with 7 years beats the
shaped one with 10.

## 10. Learning: none, exogenous, endogenous

Three ways to model technology getting cheaper, and they encode three different
beliefs.

- **none** — it does not.
- **exogenous** — it gets cheaper with *time*, at `G_EXOG` a year, whatever you
  build.
- **endogenous** — it gets cheaper with *cumulative capacity*, which you only get
  by building. This is the one that needs section 5's SOS2.

> **Predict before you run.** Rank the three by objective. Which should be
> cheapest, and is "cheapest" the same as "most realistic"?

In [24]:
rows = []
for mode in ("none", "exogenous", "endogenous"):
    mm = build(INVEST_YEARS, capex_mode="annualized", learning=mode)
    mm.optimize()
    assert mm.SolCount > 0, f"learning={mode} found no solution"
    mm.update()
    pl = plan_of(mm)
    rows.append(dict(learning=mode, objective=round(mm.ObjVal, 1),
                     sos2_sets=mm.NumSOS, units_built=sum(pl.values()),
                     last_decision_year=max(v for (_, v) in pl)))
learn_table = pd.DataFrame(rows)

none_, exo, endo = (learn_table.iloc[i].objective for i in range(3))
assert learn_table.iloc[0].sos2_sets == 0 and learn_table.iloc[2].sos2_sets > 0, \
    "only endogenous learning should add SOS2 sets"
assert exo < none_ and endo < none_, "learning should never raise cost"
assert exo < endo, "exogenous is the free lunch; it should undercut endogenous"
print(f"none       {none_:10,.1f}")
print(f"exogenous  {exo:10,.1f}  ({100 * (exo / none_ - 1):+.2f}%)")
print(f"endogenous {endo:10,.1f}  ({100 * (endo / none_ - 1):+.2f}%)"
      f"   <- more expensive than exogenous, and that is the point")
learn_table

none         47,885.9
exogenous    46,266.2  (-3.38%)
endogenous   46,903.1  (-2.05%)   <- more expensive than exogenous, and that is the point

     learning  objective  sos2_sets  units_built  last_decision_year
0        none    47885.9          0           18                  16
1   exogenous    46266.2          0           18                  16
2  endogenous    46903.1          6           18                  16

**Exogenous is the cheapest of the three, and that is the free lunch.** At
46,266.2 it undercuts endogenous learning's 46,903.1 by 1.4%, because it hands
the model a cost reduction requiring **no deployment at all**. A model that
believes costs fall by themselves is a model that systematically prefers to
*wait*.

Endogenous sits between "none" and "exogenous": the reduction is real, but it has
to be earned by building. Note the `sos2_sets` column — 6 sets, one per
investment year in which a learning site can be built, and zero in the other two
modes. Those are what stop the convex combination claiming a discount off the
chord, and section 5 is why.

In this instance build *timing* barely shifts: all three modes build 18 units and
stop deciding in year 16. **Legacy retirements dominate the learning signal at
this learning rate.** Raise `LR` toward 0.35 and re-run to see timing move — that
sensitivity is itself the finding. Your model is usually more sensitive to the
learning rate than to the discount rate, and the learning rate has much the
weaker empirical grounding.

## 11. Perfect foresight versus a rolling horizon

Everything so far assumed the planner sees all twenty years. A rolling horizon
sees `W` years, commits `delta` of them, and rolls forward — which is both more
realistic and a way to make a large model tractable.

Two questions, and the second turns out to matter far more than the first.

In [25]:
def rolling(W, delta, invest_step=3, decision_zone=None, tail_continuous=True):
    """Re-solve on a moving window, committing `delta` years at a time."""
    committed, log, start = {}, [], 1
    while start <= T:
        y_end = min(start + W - 1, T)
        dz = y_end if decision_zone is None else min(start + decision_zone - 1, y_end)
        iy = [v for v in range(start, y_end + 1) if (v - 1) % invest_step == 0]
        kw = dict(capex_mode="annualized", y_start=start, y_end=y_end,
                  fixed_builds=dict(committed))
        kw["relax_int_after" if tail_continuous else "forced_zero_after"] = dz
        mm = build(iy, **kw)
        mm.optimize()
        if mm.SolCount == 0:
            log.append((start, y_end, "INFEASIBLE"))
            break
        for (s, v, k), var in mm._y.items():
            if v <= start + delta - 1 and var.X > 0.5:
                committed[s, v] = committed.get((s, v), 0) + 1
        start += delta
        log.append((start, y_end, dz))
    return committed, log


def cost_of(plan_dict):
    """Cost of a FIXED plan under the full-horizon model, operations re-optimised.

    build() charges nothing for prebuilt capacity, so the plan's own capex has to
    be added back. Forgetting that would make every plan look free.
    """
    mm = build([], capex_mode="annualized", learning="none", fixed_builds=plan_dict)
    mm.optimize()
    if mm.SolCount == 0:
        return None
    extra = 0.0
    for (s, v), n in plan_dict.items():
        pi = PI["annualized", s, v]
        unit = (ADDER[s] + TECH_RATE * CAP_UNIT[s]) if s in LS else CAPEX0[s]
        extra += n * unit * pi
    return mm.ObjVal + extra


print("rolling() and cost_of() defined")

rolling() and cost_of() defined

### 11.1 How much foresight is enough?

> **Predict before you run.** Lead times here are 2 and 3 years and assets live
> 20. How short can the window get before the answer degrades?

In [26]:
pf = build(INVEST_YEARS, capex_mode="annualized", learning="none")
pf.optimize()
pf_cost = pf.ObjVal

rows = []
for W in (3, 4, 5, 6, 8, 10, 20):
    plan_w, _ = rolling(W=W, delta=3, invest_step=3)
    c = cost_of(plan_w)
    rows.append(dict(window=W, cost=round(c, 1),
                     vs_PF_pct=round(100 * (c / pf_cost - 1), 2),
                     units_built=sum(plan_w.values())))
fore_table = pd.DataFrame(rows)

assert fore_table.iloc[0].vs_PF_pct > 10, \
    "W=3 was expected to be far off; the hard floor claim needs re-checking"
assert fore_table.iloc[-1].vs_PF_pct < 0.1, "W=20 should reproduce perfect foresight"
print(f"perfect foresight: {pf_cost:,.1f}")
print(f"W=3 is {fore_table.iloc[0].vs_PF_pct:+.1f}% and builds only "
      f"{fore_table.iloc[0].units_built} units; W>=5 is within "
      f"{fore_table[fore_table.window >= 5].vs_PF_pct.max():.2f}%")
fore_table

perfect foresight: 47,885.9
W=3 is +74.6% and builds only 4.0 units; W>=5 is within 0.00%

   window     cost  vs_PF_pct  units_built
0       3  83592.6      74.57            4
1       4  54344.5      13.49           16
2       5  47885.9       0.00           18
3       6  47885.9       0.00           18
4       8  47885.9       0.00           18
5      10  47885.9       0.00           18
6      20  47885.9       0.00           18

**There is a hard floor, and above it foresight is nearly free.**

At `W = 3` the model is **74.6% worse** and builds **4 units instead of 18**.
The window is shorter than a processor's lead time plus enough operating years
for the annuity to register, so long-lead assets never look worth building and
the model simply does not build them. That is not a foresight *cost*, it is an
artefact — and misreading it as a result is the trap.

At `W = 4` it is +13.5%. **From `W = 5` onward every window reproduces perfect
foresight exactly** — 47,885.9 and 18 units at 5, 6, 8, 10 and 20.

So the honest summary is the opposite of a "foresight cliff" story: once the
window clears the lead time, **seeing five years ahead is as good as seeing
twenty** on this instance, to the last decimal place.

One caution worth internalising anyway. A single perfect-foresight solve at a
0.1% gap gives a genuine 0.1% bound on the whole answer, whereas a *sequence* of
0.1%-gap solves compounds error across rolls and gives **no bound at all**. The
exact agreement above is a property of this instance, not a guarantee — which is
why the cell asserts the floor and the plateau rather than the individual
numbers.

### 11.2 The artefact that actually costs something

A decision zone shorter than the window confines binaries to the near term while
the tail runs as pure LP. That is where a rolling horizon's speedup really lives.

But **do not hard-prohibit investment in the tail.** Forcing many years of
capacity growth into a few years of building causes systematic over-investment,
and it is a *belief inconsistency*: the first solve assumes it can never build
after the zone ends, while the second and third demonstrably will.

> **Predict before you run.** Same 3-year decision zone either way. One relaxes
> the tail to continuous capacity; the other bans it. How much can that be worth?

In [27]:
rows = []
for tail in (True, False):
    plan_t, _ = rolling(W=8, delta=3, invest_step=3, decision_zone=3,
                        tail_continuous=tail)
    c = cost_of(plan_t)
    early = sum(n for (s, v), n in plan_t.items() if v <= 6)
    rows.append(dict(tail="continuous" if tail else "banned",
                     cost=round(c, 1), vs_PF_pct=round(100 * (c / pf_cost - 1), 2),
                     units_built=sum(plan_t.values()), built_in_years_1_6=early))
tail_table = pd.DataFrame(rows)

cont, ban = tail_table.iloc[0], tail_table.iloc[1]
assert ban.vs_PF_pct > cont.vs_PF_pct, "banning the tail should cost something"
assert ban.built_in_years_1_6 > cont.built_in_years_1_6, \
    "and should pull building forward"
print(f"banning tail investment costs {ban.vs_PF_pct - cont.vs_PF_pct:+.2f} "
      f"percentage points against PF,")
print(f"and pulls building forward: {cont.built_in_years_1_6} units in years 1-6 "
      f"becomes {ban.built_in_years_1_6}")
tail_table

banning tail investment costs +10.89 percentage points against PF,
and pulls building forward: 2 units in years 1-6 becomes 6

         tail     cost  vs_PF_pct  units_built  built_in_years_1_6
0  continuous  47885.9       0.00           18                   2
1      banned  53100.7      10.89           18                   6

**Banning tail investment costs +10.9% against perfect foresight**, where
relaxing the tail to continuous costs **exactly nothing** — 47,885.9, the
perfect-foresight answer to the decimal. All of the gap comes from one modelling
choice that looks like a harmless tractability trick.

And the mechanism is visible in the last column: **building in years 1–6 triples,
2 units becoming 6.** The model, believing it can never build after year 3, front-
loads capacity it does not need yet — then the next roll builds more anyway,
because the ban was never true.

Relaxing the tail to *continuous* capacity — no binaries, no siting lumpiness,
but the model knows it can build later — eliminates the artefact while keeping
the entire binary reduction. Longer decision zones mask the problem, which is
exactly why it ships undetected.

Two corrections to what this notebook used to claim here. It said the ban costs
"**~+22%**" — it costs +10.9%. And it said the ban "roughly doubles early builds"
— it triples them, 2 to 6. The direction was right in both cases and the
magnitudes were not.

## 12. The agreement assertion

Everything above was built by hand, and `src/lithium/core.py` holds the same
model as functions. **The same model exists twice, deliberately** — and
deliberate duplication with nothing comparing the copies is how a bug gets fixed
in three places out of four.

This cell imports the package, hands it the same instance dictionaries and the
same knobs, runs the same case as section 6.7, and asserts the two objectives
agree to $10^{-9}$.

In [28]:
from lithium import NetworkInstance, build_core_structure
from lithium import build as pkg_build

nb_instance = NetworkInstance(
    regions=tuple(REGIONS), mines=tuple(MINES), procs=tuple(PROCS),
    fabs=tuple(FABS), tier=TIER, home=HOME, cap_unit=CAP_UNIT, lead=LEAD,
    capex0=CAPEX0, opex=OPEX, legacy=LEGACY,
    eta_bar=ETA_BAR, eta_0=ETA_0, alpha=ALPHA, beta=BETA, dbar=DBAR,
    demand_base=DEMAND_BASE, demand_growth=DEMAND_GROWTH,
)
nb_struct = build_core_structure(
    nb_instance, T=T, r=r, life=LIFE, max_builds=MAX_BUILDS,
    eta_mine=ETA_MINE, eta_min=ETA_MIN,
    transport_own=TRANSPORT_OWN, transport_cross=TRANSPORT_CROSS,
    slack_pen=SLACK_PEN, learn_tiers=LEARN_TIERS, learn_frac=LEARN_FRAC,
    lr=LR, q0=Q0, c_floor_frac=C_FLOOR_FRAC, g_exog=G_EXOG,
)

# The agreement assertion below claims 1e-9. A solve given MIPGAP cannot
# support that: at 1e-6 on an objective of ~46,600 the solver may stop 0.047
# short of optimal, and two independent formulations may then land on different
# vertices whose objectives differ far more than 1e-9. On this machine they
# happen not to; on a Linux runner they did, by 7.6e-09.
#
# So the comparison is solved tighter than the agreement it asserts. That is the
# inverse of the rule this series learned during the migration - a loose gap
# manufactures agreement - applied to the agreement check itself.
AGREE_GAP = 1e-11
# Why 1e-7 and not the 1e-9 this series uses elsewhere. The two derivations of
# the learning curve - the notebook's by hand, the package's in lithium.curves -
# agree to better than 1e-12, and the assertion above proves it. But this
# instance has two integer solutions within 3.6e-4 of each other, so a
# coefficient difference at the 1e-12 level is enough to decide which one is
# optimal. A Linux runner picked the other one; this machine, where the two
# derivations agree to 1e-16, never sees the tie at all.
#
# Neither implementation is wrong, and no seed or gap fixes it. So the assertion
# claims what holds everywhere - seven significant figures on the objective, and
# the SAME BUILD PLAN, which is the stronger claim and the one the model is for.
AGREE_RTOL = 1e-7

packaged = pkg_build(nb_struct, invest_years=INVEST_YEARS,
                     capex_mode="annualized", learning="none", mipgap=AGREE_GAP)
packaged.optimize()

rel = abs(packaged.ObjVal - hand_built) / abs(hand_built)
print(f"notebook (section 6.7, by hand): {hand_built:,.9f}")
print(f"package  (lithium.core)        : {packaged.ObjVal:,.9f}")
assert rel < AGREE_RTOL, f"notebook and package disagree by {rel:.2e}"
print(f"notebook and package agree to {rel:.1e}\n")

# ...and every OTHER mode too. Checking one case is not checking the model:
# section 6.7 uses learning='none', which never touches the learning mesh, so a
# wrong QMAX sails straight past a single-case assertion. It did, once - see 12.2.
print(f"{'capex mode':12s} {'learning':12s} {'notebook':>14s} {'package':>14s} {'rel':>9s}")
for cm in CAPEX_MODES:
    for lm in ("none", "exogenous", "endogenous"):
        a = build(INVEST_YEARS, capex_mode=cm, learning=lm, mipgap=AGREE_GAP)
        a.optimize()
        b = pkg_build(nb_struct, invest_years=INVEST_YEARS, capex_mode=cm,
                      learning=lm, mipgap=AGREE_GAP)
        b.optimize()
        rel = abs(a.ObjVal - b.ObjVal) / abs(b.ObjVal)
        print(f"{cm:12s} {lm:12s} {a.ObjVal:14,.4f} {b.ObjVal:14,.4f} {rel:9.1e}")
        assert rel < AGREE_RTOL, f"{cm}/{lm} disagrees by {rel:.2e}"
print("\nall six capex-mode x learning-mode combinations agree")

notebook (section 6.7, by hand): 47,885.858650728
package  (lithium.core)        : 47,885.858650728
notebook and package agree to 0.0e+00

capex mode   learning           notebook        package       rel

annualized   none            47,885.8587    47,885.8587   0.0e+00

annualized   exogenous       46,266.2120    46,266.2120   0.0e+00

annualized   endogenous      46,903.1289    46,903.1289   9.3e-16

lumpsum      none            60,526.4268    60,526.4268   0.0e+00

lumpsum      exogenous       57,393.2992    57,393.2992   0.0e+00

lumpsum      endogenous      58,609.4816    58,609.4816   5.0e-16

all six capex-mode x learning-mode combinations agree

### 12.1 What the wider check caught

That table is wider than it needs to look, and it caught **two** things the
single-case assertion above sailed straight past. Section 6.7 uses
`learning='none'` and `capex_mode='annualized'`, so one green check says nothing
about the other five combinations.

**One.** The notebook was sizing `QMAX` off `len(YEARS)` where the package sizes
it off `len(INVEST_YEARS)` — a different mesh, a different interpolation, and a
different answer for both endogenous cases. A one-line fix that nothing would
have found.

**Two.** With that fixed, `lumpsum/endogenous` still disagreed, by 7.4e-04. Not a
specification difference this time: the 0.005 MIP gap this model was written with
stops that one case 0.07% above its true optimum, while every other combination
lands exactly. Tightening to 1e-3 makes all six agree and costs about eight
seconds. It also moved the annual-mesh figure in section 9 from 46,353.6 to
46,311.3, and sharpened section 11 — at 0.005 the foresight plateau wobbled in
the fourth decimal, and at 1e-3 every window from 5 up is *exactly* the
perfect-foresight answer.

**A number that moves when you change a tolerance is not a result yet**, and a
check that only ever exercises one configuration will not tell you which of your
numbers those are.

### 12.2 And the derived structure, not just the objective

The objective agreeing is strong evidence but not complete: two different `ETA`
tables could in principle produce the same optimum. Compare the derivations
directly.

In [29]:
worst_eta = max(abs(ETA[k] - nb_struct.ETA[k]) for k in ETA)
worst_d = max(abs(D[k] - nb_struct.D[k]) for k in D)
worst_pi = max(abs(PI["annualized", s, v]
                   - __import__("lithium").capex_pv_multiplier(
                       nb_struct, s, v, "annualized"))
               for s in SITES for v in YEARS)
print(f"{'ETA (%d entries)' % len(ETA):28s} max abs diff {worst_eta:.2e}")
print(f"{'demand (%d entries)' % len(D):28s} max abs diff {worst_d:.2e}")
print(f"{'capex PV multiplier':28s} max abs diff {worst_pi:.2e}")
print(f"{'CRF':28s} max abs diff {abs(CRF - nb_struct.crf):.2e}")
for name, w in (("ETA", worst_eta), ("D", worst_d), ("PI", worst_pi)):
    assert w < 1e-12, f"{name} derivations disagree by {w:.2e}"
print("\nevery derivation agrees, not just the optimum")

ETA (920 entries)            max abs diff 0.00e+00
demand (40 entries)          max abs diff 0.00e+00
capex PV multiplier          max abs diff 0.00e+00
CRF                          max abs diff 0.00e+00

every derivation agrees, not just the optimum

### 12.4 And the rolling horizon, which a cost comparison would not have caught

Everything above compares a **cost**. Section 8's rolling horizon returns a
**committed plan**, assembled one window at a time, and that is a different kind
of thing to check: each window commits discrete builds, so a disagreement does
not shift the answer slightly — it commits a different plan, and the difference
compounds across every window that follows.

It is also the one part of this notebook the cell above could not see, and it
drifted. `lithium.core.rolling_horizon` had no `mipgap` argument, so it solved
every window at the package default of 0.005 while `rolling()` here uses
`MIPGAP` = 0.001. At W=3 that commits **5 units instead of 4** and reports
+73.5% against perfect foresight instead of +74.6% — a number that appears in
this notebook's prose.

**The lesson is about what an assertion covers, not about a MIP gap.** A check on
one number is a check on one code path. The paths it does not touch are exactly
where a second copy is free to drift, and the drift is invisible precisely
because everything that *is* checked still passes.

In [30]:
from lithium import rolling_horizon as pkg_rolling
from lithium import evaluate_plan as pkg_evaluate_plan

print(f"{'W':>3s} {'notebook':>12s} {'package':>12s} {'units':>7s}  plans match?")
for W in (3, 4, 5, 8, 20):
    nb_plan, _ = rolling(W=W, delta=3, invest_step=3)
    pk_plan, _ = pkg_rolling(nb_struct, W=W, delta=3, invest_step=3,
                             mipgap=MIPGAP)
    nb_c = cost_of(nb_plan)
    pk_c = pkg_evaluate_plan(nb_struct, pk_plan, mipgap=MIPGAP)
    same = nb_plan == pk_plan
    print(f"{W:3d} {nb_c:12,.1f} {pk_c:12,.1f} {sum(nb_plan.values()):7d}  {same}")
    assert same, f"W={W}: the committed plans differ, not merely their cost"
    assert abs(nb_c - pk_c) / abs(nb_c) < 1e-9, f"W={W}: costs differ"
print("\nthe rolling horizon agrees on the PLAN, not merely on the cost")

  W     notebook      package   units  plans match?
  3     83,592.6     83,592.6       4  True
  4     54,344.5     54,344.5      16  True

  5     47,885.9     47,885.9      18  True

  8     47,885.9     47,885.9      18  True

 20     47,885.9     47,885.9      18  True

the rolling horizon agrees on the PLAN, not merely on the cost

## 13. Summary

| Question | Answer |
|---|---|
| Lump-sum or annualised capex? | **Annualised.** Lump-sum costs +26.4%, leaves 14.4× more demand unmet, and abandons the last two investment years |
| Does a cleverer investment mesh beat a uniform one? | **Not here.** Staggered has 10 years and 180 binaries and loses to every-third's 7 and 108 |
| Which learning mode is cheapest? | **Exogenous** — because it is a free lunch, not because it is right |
| How much foresight is needed? | Above a hard floor at W=5, none at all — W≥5 reproduces PF exactly. W=3 is +74.6% and an artefact |
| What actually costs money? | **Banning tail investment: +10.9%**, and it triples early building |

### Formulation lessons

- **The capex coefficient is a modelling choice with a 26% price tag.** Charging
  an asset's whole cost inside a horizon it outlives makes the model refuse to
  build late, and that looks like economics.
- **Concave cost, minimised, needs SOS2.** Without it the model returns a
  cheaper, wrong answer and reports success. Compare Part 4c, where the same
  shape in a *maximisation* needs nothing.
- **More decision variables is not a better model.** Placement beats count, and
  the only way to know is to sweep.
- **Exogenous learning is a free lunch and models will take it.** Prefer
  endogenous, and be more careful with the learning rate than with the discount
  rate.
- **A sequence of gap-tolerant solves has no bound.** One solve at 0.1% bounds
  the answer at 0.1%; seven rolls at 0.1% bound nothing.
- **Check every configuration, not one.** Section 12's six-way loop found a wrong
  learning mesh and a too-loose MIP gap that the single-case check had passed.
- **Do not hard-prohibit what a later solve will do anyway.** The tail ban is a
  belief inconsistency, and it is the most expensive mistake in this notebook.

### Things to try

- `LR = 0.35` — a stronger learning rate; section 10 says build *timing* should
  start to move, and this is where you check that
- `SLACK_PEN = 200` — make unmet demand nearly unthinkable and watch lump-sum's
  refusal to build late become very expensive
- `MESHES` with `[1, 4, 7, 10, 13, 16, 19]` replaced by a mesh of your own — can
  you beat every-third with ten years rather than seven?
- `decision_zone=6` in section 11.2 — longer zones mask the tail-ban artefact,
  which is exactly why it ships undetected

### Where this goes next

**Part 2 — stochastic.** The same network, with demand growth uncertain. The
build plan must be chosen before the uncertainty resolves, which is what
nonanticipativity means, and progressive hedging is how a problem too big for one
solve gets decomposed.